"""initial schema

Revision ID: 16b9b6672f34
Revises: 
Create Date: 2026-02-10 22:51:21.116503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16b9b6672f34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('instagram_handle', sa.String(length=255), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_instagram_handle'), 'brands', ['instagram_handle'], unique=True)
    op.create_table('influencers',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('instagram_handle', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('profile_pic_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencers_instagram_handle'), 'influencers', ['instagram_handle'], unique=True)
    op.create_table('audits',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brand_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('progress', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('influencer_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_brand_id'), 'audits', ['brand_id'], unique=False)
    op.create_table('audience_overlaps',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('audit_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('influencer_a_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('influencer_b_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('overlap_percentage', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['influencer_a_id'], ['influencers.id'], ),
    sa.ForeignKeyConstraint(['influencer_b_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'influencer_a_id', 'influencer_b_id', name='uq_audit_influencer_pair')
    )
    op.create_index(op.f('ix_audience_overlaps_audit_id'), 'audience_overlaps', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audience_overlaps_influencer_a_id'), 'audience_overlaps', ['influencer_a_id'], unique=False)
    op.create_index(op.f('ix_audience_overlaps_influencer_b_id'), 'audience_overlaps', ['influencer_b_id'], unique=False)
    op.create_table('audit_influencers',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('audit_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('influencer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('discovery_source', sa.String(length=100), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('avg_likes', sa.Float(), nullable=True),
    sa.Column('avg_comments', sa.Float(), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('fraud_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_quality_score', sa.Float(), nullable=True),
    sa.Column('content_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audience_demographics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audience_quality_score', sa.Float(), nullable=True),
    sa.Column('estimated_reach', sa.Integer(), nullable=True),
    sa.Column('estimated_cpm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_influencers_audit_id'), 'audit_influencers', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_influencers_influencer_id'), 'audit_influencers', ['influencer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_influencers_influencer_id'), table_name='audit_influencers')
    op.drop_index(op.f('ix_audit_influencers_audit_id'), table_name='audit_influencers')
    op.drop_table('audit_influencers')
    op.drop_index(op.f('ix_audience_overlaps_influencer_b_id'), table_name='audience_overlaps')
    op.drop_index(op.f('ix_audience_overlaps_influencer_a_id'), table_name='audience_overlaps')
    op.drop_index(op.f('ix_audience_overlaps_audit_id'), table_name='audience_overlaps')
    op.drop_table('audience_overlaps')
    op.drop_index(op.f('ix_audits_brand_id'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_influencers_instagram_handle'), table_name='influencers')
    op.drop_table('influencers')
    op.drop_index(op.f('ix_brands_instagram_handle'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
